name: Seed Cachix

on:
  push:
    branches:
      - main
      - rel-*
    tags:
      - v*
  pull_request:
    branches:
      - main
      - rel-*

jobs:
  Seed-Cachix-Linux:
    name: Seed Cachix on Linux (including static)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Nix Environment
        uses: ./.github/actions/setup-nix

      - name: nix info
        run: |
          nix --version

      - name: Install cachix tooling (raw nixpkgs)
        run: |
          nix-env -f default.nix -iA cachixToolsRaw.bin
